// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4-FDuuZueZpyRQk5GN5qlNSMPA05H6Tc',
    appId: '1:140890129619:web:adb365310885cd4c6dc026',
    messagingSenderId: '140890129619',
    projectId: 'expensetracker92-882ea',
    authDomain: 'expensetracker92-882ea.firebaseapp.com',
    storageBucket: 'expensetracker92-882ea.appspot.com',
    measurementId: 'G-X6G0Y13SLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtIcSof8aLYCUWHDyjCF2vNcz8yKFTmU',
    appId: '1:140890129619:android:4217c1f0bd867cc26dc026',
    messagingSenderId: '140890129619',
    projectId: 'expensetracker92-882ea',
    storageBucket: 'expensetracker92-882ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUoCM0ooBiU5LFTZFcCr0hm8y6YdxTV04',
    appId: '1:140890129619:ios:fc56a9a9c87e28b96dc026',
    messagingSenderId: '140890129619',
    projectId: 'expensetracker92-882ea',
    storageBucket: 'expensetracker92-882ea.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUoCM0ooBiU5LFTZFcCr0hm8y6YdxTV04',
    appId: '1:140890129619:ios:a42c126a705675746dc026',
    messagingSenderId: '140890129619',
    projectId: 'expensetracker92-882ea',
    storageBucket: 'expensetracker92-882ea.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
